### ISSUE TITLE
Export results as CSV 

### ISSUE THREAD

**Issue by KarelBerka** [IFB-ElixirFr/FAIR-checker#18]
Currently, it is not possible to copy-paste results anywhere to make e.g. comparisons. 
Simple CSV as a download with tested resource identifier would be great for such use of the service.

**Comment by thomasrosnet** [comment]
Hello, thanks for the message and sorry for the late reply about this issue, we fixed it in #76 .
If you have any other question or suggestions do not hesitate to contact us.
