### ISSUE TITLE
Rule delegation in I1B to F2A

### ISSUE THREAD

**Issue by MaillPierre** [IFB-ElixirFr/FAIR-checker#197]
In `metrics/I1B_Impl.py`, the verification "that at least one used ontology class or property is known in major ontology registries (OLS, BioPortal, LOV)" is delegated to F2A.
However, `metrics/F2A_Impl.py`  verifies "that at least one RDF triple can be found in metadata", `metrics/F2B_Impl.py` is the one that "that at least one used ontology class or property are known in major ontology registries (OLS, BioPortal, LOV)"

Is it deliberate?

**Comment by albangaignard** [comment]
Thanks @MaillPierre for your feedback. These two metrics are part of the source code but are not instanciated during the FAIR assesment. I close the issue.
