### ISSUE TITLE
web app link not functional

### ISSUE THREAD

**Issue by Neiluj49** [IFB-ElixirFr/FAIR-checker#202]
Hello,
I'd like testing the Fair-Checker web app.
Unfortunately, it seems to be not functionnal.
Please, could you keep on eye on it and fix ?
Cheers !

**Comment by albangaignard** [comment]
Dear @Neiluj49, thanks for your feedback, the service has been down during technical maintainance and everything seems to be ok now: web interface at https://fair-checker.france-bioinformatique.fr and API at https://fair-checker.france-bioinformatique.fr/swagger. Please tell me if you still have access issues.
