### ISSUE TITLE
FAIR-Checker internal server error

### ISSUE THREAD

**Issue by hexylena** [IFB-ElixirFr/FAIR-checker#212]
Hello ! Not sure if it is a known issue but I wanted to report it in case it was not. I'm attempting to run fair-checker for some URLs but it was just "processing" with a loading icon and no results were being returned.

I've checked against the API in case it was an error message I was not receiving, but there I receive a 500 internal server error. 

E.g. 
https://fair-checker.france-bioinformatique.fr/api/check/metric_A1.1?url=https%3A%2F%2Fbio.tools%2Fjaspar
https://fair-checker.france-bioinformatique.fr/api/check/metric_A1.1?url=https%3A%2F%2Ftraining.galaxyproject.org%2Ftraining-material%2Ftopics%2Fadmin%2Ftutorials%2Fansible-galaxy%2Ftutorial.html

Thank you for providing this nice service !

**Comment by albangaignard** [comment]
Dear @hexylena, thanks for reporting this issue, something went wrong on the server. I restarted it and everything is  working now. Please re-open the issue or contact me directly by email if you face another strange behaviour for FAIR-Checker.

**Comment by hexylena** [comment]
Oh thank you @albangaignard ! Great to hear :)
